<?php

define('MYSQL_HOST', 'MYSQL_HOST_SECRET');
define('MYSQL_DATABASE', 'MYSQL_DATABASE_SECRET');
define('MYSQL_USERNAME', 'MYSQL_USERNAME_SECRET');
define('MYSQL_PASSWORD', 'MYSQL_PASSWORD_SECRET');